slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_slam_toolbox: true
    resolution: 0.05        
    # if your odom is decent, keep loop closure on; else you can start simple:
    do_loop_closing: false
    mode: localization               # (mapping | localization | lifelong)
    map_file_name: /home/mr/map1
    map_start_pose: [0.0, 0.0, 0.0]
