slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_scan_matching: true
    use_slam_toolbox: true
    resolution: 0.05            # map resolution (m/cell)
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.17
    transform_publish_period: 0.02
    map_update_interval: 2.0
    # if your odom is decent, keep loop closure on; else you can start simple:
    enable_interactive_mode: false
    mode: mapping               # (mapping | localization | lifelong)
